/**
  * @file aht20.h
  * @brief AHT20温湿度传感器驱动头文件
  * @author Generated by AI
  */

#ifndef __AHT20_H__
#define __AHT20_H__

#include "main.h"
#include "i2c.h"

// AHT20 I2C地址定义
#define AHT20_I2C_ADDR        0x38  // 7位地址
#define AHT20_WRITE_ADDR      (AHT20_I2C_ADDR << 1)  // 写地址 0x70
#define AHT20_READ_ADDR       ((AHT20_I2C_ADDR << 1) | 1)  // 读地址 0x71

// AHT20命令定义
#define AHT20_CMD_INIT        0xBE  // 初始化命令
#define AHT20_CMD_MEASURE     0xAC  // 触发测量命令

// AHT20状态字位定义
#define AHT20_STATUS_BUSY     0x80  // Bit7: 忙闲指示 (1=忙, 0=闲)
#define AHT20_STATUS_CAL      0x08  // Bit3: 校准使能 (1=已校准, 0=未校准)

// 函数声明
HAL_StatusTypeDef AHT20_ReadStatus(uint8_t *status);  // 读取状态字
HAL_StatusTypeDef AHT20_WriteCmd(uint8_t cmd, uint8_t param1, uint8_t param2);  // 发送命令
HAL_StatusTypeDef AHT20_ReadData(uint8_t *buffer, uint8_t len);  // 读取数据
HAL_StatusTypeDef AHT20_Init(void);  // 初始化传感器
HAL_StatusTypeDef AHT20_Measure(float *humidity, float *temperature);  // 测量温湿度

#endif /* __AHT20_H__ */